#!/bin/bash
export PATH=$PATH:/bin:/usr/bin:/home/jacob/.local/scripts
# executed by cron vs executed in terminal get different results caused by env!
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
#export DISPLAY=:0

CLOCK=`date +\%H`

bell() {
    if [ $CLOCK -gt 7 ] && [ $CLOCK -lt 20 ]
    then
        /usr/bin/paplay /home/jacob/.local/scripts/07-19.ogg
    else
        /usr/bin/paplay /home/jacob/.local/scripts/20-06.ogg
    fi
    }

bell

/usr/bin/notify-send -t 2000 -i /home/jacob/.local/scripts/alarm-clock.svg "$CLOCK 点整"

/usr/bin/espeak -vzh "$CLOCK 点整"

# add below line by exec "crontab -e"
# 0 * * * * /bin/bash ~/.local/scripts/alarm
